### ISSUE TITLE
"Type[Model]" has no attribute "objects"

### ISSUE THREAD

**Issue by SpamapS** [mkurnikov/django-stubs#16]
Not sure what to do, having to type: ignore the second line below:

```python
User = django.contrib.auth.get_user_model()
user = User.objects.create_user(email=data.get("email"), signup_nonce=signup_nonce)
```

**Comment by K0Te** [comment]
Hi,

Did you enable Mypy plugin ?
I've had similar errors without plugin enabled:
```
[mypy]
plugins =
    mypy_django_plugin.main
```

**Comment by mkurnikov** [comment]
If it won't help, please provide project as an example. It's probably an issue with the plugin not being able to set `objects` before you call this line (import cycle somewhere). Simple reproduce would be very helpful.

**Comment by SpamapS** [comment]
Um, I was intending on working on a simple reproduce. Why would you close this? It's valid data pointing at a bug.. :-P

**Comment by mkurnikov** [comment]
Try latest master, it should be fixed now.

**Comment by SpamapS** [comment]
Confirmed, works with master. Can haz release! ;) Also thanks!
