### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by lucassouto** [mkurnikov/django-stubs#2]
When I try to use the plugin it returns me this error:
`mypy.ini:2: error: Error importing plugin 'mypy_django_plugin.main'`

mypy.ini:
```
[mypy]
plugins =
    mypy_django_plugin.main
```

pip freeze:
**django-stubs==0.1.0**

**Comment by mkurnikov** [comment]
Could you try on the latest `master`?

**Comment by lucassouto** [comment]
I installed it with the latest updates but now it gives me an error in **DJANGO_SETTINGS_MODULE**: `mypy: can't find module 'config.settings.local'`

My project structure:

> .
> ├── config
> │   ├── __init__.py
> │   ├── nginx
> │   │   └── conf.d
> │   ├── settings
> │   │   ├── base.py
> │   │   ├── local.py
> │   │   ├── production.py
> │   │   └── test.py
> │   ├── urls.py
> │   └── wsgi.py
> ├── docker-compose.yml
> ├── docker-entrypoint.sh
> ├── Dockerfile
> ├── experience_backend
> ├── manage.py
> ├── mypy.ini
> ├── Pipfile
> ├── Pipfile.lock
> ├── pylava.ini
> ├── pytest.ini
> ├── README.md
> ├── setup.py
> ├── tox.ini
> └── utility

**Comment by lucassouto** [comment]
I worked, thanks
