### ISSUE TITLE
Consider changing the project license to MIT

### ISSUE THREAD

**Issue by w0rp** [mkurnikov/django-stubs#21]
I would like to propose that the project's license be changed to an MIT license. I have had problems in the past with organising developer efforts to contribute to projects with a 3-clause BSD licence. The third clause prohibiting promotion without consent raises concerns around promoting developer hackathons for working on projects. I'd prefer to be able to promote a hackathon for contributing to free software projects without having to first ask for consent. A 2-clause BSD licence would also be fine.

Thank you!

**Comment by mkurnikov** [comment]
Thanks for helpful suggestion, done.

**Comment by w0rp** [comment]
Thank you! You might want to split the lines of text so they fit in terminals too.
