### ISSUE TITLE
Suggestion: Add to PyPi

### ISSUE THREAD

**Issue by sbdchd** [mkurnikov/django-stubs#3]
What are your thoughts on adding this project to https://pypi.org to make it easier to install and use?

**Comment by mkurnikov** [comment]
I wanted to wait for mypy 0.660, because there was a couple of bugs in 0.650 which are important for the plugin. Now it just requires mypy from github as a dependency, I'm not sure whether it's a correct way.

**Comment by mkurnikov** [comment]
@sbdchd 
I've added it to pypi, could you check whether it works correctly for you?

**Comment by mkurnikov** [comment]
Does it work properly with 0.660?

**Comment by sbdchd** [comment]
I upgraded to `mypy --version 0.666` and it is working.

Thanks!

**Comment by sbdchd** [comment]
While installing the stubs works, the mypy plugin doesn't seem to be working.

```
plugins =
    mypy_django_plugin.main
```

which gives the following error:

```
tox.ini:40:1: error: Error importing plugin 'mypy_django_plugin.main'
```

This might be related to #2

**Comment by sbdchd** [comment]
`site-packages/` does include `mypy_django_plugin`, but my setup is a little weird as I'm using [`poetry`](https://github.com/sdispater/poetry) to manage mydependencies.

I have `mypy` configured through a `tox.ini` file that is in the same directory as the `virtualenv`, `.venv/`.

**Comment by mkurnikov** [comment]
Could you create a new issue mentioning poetry here, with some steps to reproduce? I don't have any experience with poetry, but maybe others do.
